// Code generated by protoc-gen-go-flags. DO NOT EDIT.
// versions:
// - protoc-gen-go-flags v0.0.0-dev
// - protoc              v3.17.3
// source: lorawan-stack/api/keys.proto

package ttnpb

import (
	flagsplugin "github.com/TheThingsIndustries/protoc-gen-go-flags/flagsplugin"
	pflag "github.com/spf13/pflag"
	custom_flags "go.thethings.network/lorawan-stack/v3/cmd/ttn-lw-cli/custom_flags"
)

// AddSelectFlagsForKeyEnvelope adds flags to select fields in KeyEnvelope.
func AddSelectFlagsForKeyEnvelope(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("key", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("key", prefix), false)))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("kek-label", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("kek-label", prefix), false)))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("encrypted-key", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("encrypted-key", prefix), false)))
}

// SelectFromFlags outputs the fieldmask paths forKeyEnvelope message from select flags.
func PathsFromSelectFlagsForKeyEnvelope(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	key, keySelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("key", prefix))
	if err != nil {
		return paths, err
	}
	if keySelect && key {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("key", prefix)))
	}
	kekLabel, kekLabelSelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("kek-label", prefix))
	if err != nil {
		return paths, err
	}
	if kekLabelSelect && kekLabel {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("kek-label", prefix)))
	}
	encryptedKey, encryptedKeySelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("encrypted-key", prefix))
	if err != nil {
		return paths, err
	}
	if encryptedKeySelect && encryptedKey {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("encrypted-key", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForKeyEnvelope adds flags to select fields in KeyEnvelope.
func AddSetFlagsForKeyEnvelope(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(custom_flags.New16BytesFlag(flagsplugin.Prefix("key", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("kek-label", prefix), ""))
	flags.AddFlag(flagsplugin.NewBytesFlag(flagsplugin.Prefix("encrypted-key", prefix), ""))
}

// SetFromFlags sets the KeyEnvelope message from flags.
func (m *KeyEnvelope) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	key, keySet, err := custom_flags.GetAESKey(flags, flagsplugin.Prefix("key", prefix))
	if err != nil {
		return paths, err
	}
	if keySet {
		m.Key = &key
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("key", prefix)))
	}
	kekLabel, kekLabelSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("kek-label", prefix))
	if err != nil {
		return paths, err
	}
	if kekLabelSet {
		m.KekLabel = kekLabel
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("kek-label", prefix)))
	}
	encryptedKey, encryptedKeySet, err := flagsplugin.GetBytes(flags, flagsplugin.Prefix("encrypted-key", prefix))
	if err != nil {
		return paths, err
	}
	if encryptedKeySet {
		m.EncryptedKey = encryptedKey
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("encrypted-key", prefix)))
	}
	return paths, nil
}

// AddSelectFlagsForRootKeys adds flags to select fields in RootKeys.
func AddSelectFlagsForRootKeys(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("root-key-id", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("root-key-id", prefix), false)))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("app-key", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("app-key", prefix), true)))
	AddSelectFlagsForKeyEnvelope(flags, flagsplugin.Prefix("app-key", prefix))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("nwk-key", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("nwk-key", prefix), true)))
	AddSelectFlagsForKeyEnvelope(flags, flagsplugin.Prefix("nwk-key", prefix))
}

// SelectFromFlags outputs the fieldmask paths forRootKeys message from select flags.
func PathsFromSelectFlagsForRootKeys(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	rootKeyId, rootKeyIdSelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("root-key-id", prefix))
	if err != nil {
		return paths, err
	}
	if rootKeyIdSelect && rootKeyId {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("root-key-id", prefix)))
	}
	appKey, appKeySelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("app-key", prefix))
	if err != nil {
		return paths, err
	}
	if appKeySelect && appKey {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("app-key", prefix)))
	}
	if selectPaths, err := PathsFromSelectFlagsForKeyEnvelope(flags, flagsplugin.Prefix("app-key", prefix)); err != nil {
		return paths, err
	} else {
		paths = append(paths, selectPaths...)
	}
	nwkKey, nwkKeySelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("nwk-key", prefix))
	if err != nil {
		return paths, err
	}
	if nwkKeySelect && nwkKey {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("nwk-key", prefix)))
	}
	if selectPaths, err := PathsFromSelectFlagsForKeyEnvelope(flags, flagsplugin.Prefix("nwk-key", prefix)); err != nil {
		return paths, err
	} else {
		paths = append(paths, selectPaths...)
	}
	return paths, nil
}

// AddSetFlagsForRootKeys adds flags to select fields in RootKeys.
func AddSetFlagsForRootKeys(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("root-key-id", prefix), ""))
	AddSetFlagsForKeyEnvelope(flags, flagsplugin.Prefix("app-key", prefix))
	AddSetFlagsForKeyEnvelope(flags, flagsplugin.Prefix("nwk-key", prefix))
}

// SetFromFlags sets the RootKeys message from flags.
func (m *RootKeys) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	rootKeyId, rootKeyIdSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("root-key-id", prefix))
	if err != nil {
		return paths, err
	}
	if rootKeyIdSet {
		m.RootKeyId = rootKeyId
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("root-key-id", prefix)))
	}
	appKeySet := flagsplugin.IsAnyPrefixSet(flags, flagsplugin.Prefix("app-key", prefix))
	if appKeySet {
		m.AppKey = &KeyEnvelope{}
		if setPaths, err := m.AppKey.SetFromFlags(flags, flagsplugin.Prefix("app-key", prefix)); err != nil {
			return paths, err
		} else {
			paths = append(paths, setPaths...)
		}
	}
	nwkKeySet := flagsplugin.IsAnyPrefixSet(flags, flagsplugin.Prefix("nwk-key", prefix))
	if nwkKeySet {
		m.NwkKey = &KeyEnvelope{}
		if setPaths, err := m.NwkKey.SetFromFlags(flags, flagsplugin.Prefix("nwk-key", prefix)); err != nil {
			return paths, err
		} else {
			paths = append(paths, setPaths...)
		}
	}
	return paths, nil
}
