// Code generated by protoc-gen-go-flags. DO NOT EDIT.
// versions:
// - protoc-gen-go-flags v0.0.0-dev
// - protoc              v3.17.3
// source: lorawan-stack/api/search_services.proto

package ttnpb

import (
	flagsplugin "github.com/TheThingsIndustries/protoc-gen-go-flags/flagsplugin"
	gogo "github.com/TheThingsIndustries/protoc-gen-go-flags/gogo"
	pflag "github.com/spf13/pflag"
)

// AddSetFlagsForSearchApplicationsRequest adds flags to select fields in SearchApplicationsRequest.
func AddSetFlagsForSearchApplicationsRequest(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("deleted", prefix), ""))
}

// SetFromFlags sets the SearchApplicationsRequest message from flags.
func (m *SearchApplicationsRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	deleted, deletedSet, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("deleted", prefix))
	if err != nil {
		return paths, err
	}
	if deletedSet {
		m.Deleted = deleted
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("deleted", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSearchClientsRequest adds flags to select fields in SearchClientsRequest.
func AddSetFlagsForSearchClientsRequest(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("state", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("deleted", prefix), ""))
}

// SetFromFlags sets the SearchClientsRequest message from flags.
func (m *SearchClientsRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	state, stateSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("state", prefix))
	if err != nil {
		return paths, err
	}
	if stateSet {
		for _, v := range state {
			enumValue, err := flagsplugin.SetEnumString(v, State_value)
			if err != nil {
				return paths, err
			}
			m.State = append(m.State, State(enumValue))
		}
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("state", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	deleted, deletedSet, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("deleted", prefix))
	if err != nil {
		return paths, err
	}
	if deletedSet {
		m.Deleted = deleted
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("deleted", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSearchGatewaysRequest adds flags to select fields in SearchGatewaysRequest.
func AddSetFlagsForSearchGatewaysRequest(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("eui-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("deleted", prefix), ""))
}

// SetFromFlags sets the SearchGatewaysRequest message from flags.
func (m *SearchGatewaysRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	euiContains, euiContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("eui-contains", prefix))
	if err != nil {
		return paths, err
	}
	if euiContainsSet {
		m.EuiContains = euiContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("eui-contains", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	deleted, deletedSet, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("deleted", prefix))
	if err != nil {
		return paths, err
	}
	if deletedSet {
		m.Deleted = deleted
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("deleted", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSearchOrganizationsRequest adds flags to select fields in SearchOrganizationsRequest.
func AddSetFlagsForSearchOrganizationsRequest(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("deleted", prefix), ""))
}

// SetFromFlags sets the SearchOrganizationsRequest message from flags.
func (m *SearchOrganizationsRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	deleted, deletedSet, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("deleted", prefix))
	if err != nil {
		return paths, err
	}
	if deletedSet {
		m.Deleted = deleted
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("deleted", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSearchUsersRequest adds flags to select fields in SearchUsersRequest.
func AddSetFlagsForSearchUsersRequest(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("state", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("deleted", prefix), ""))
}

// SetFromFlags sets the SearchUsersRequest message from flags.
func (m *SearchUsersRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	state, stateSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("state", prefix))
	if err != nil {
		return paths, err
	}
	if stateSet {
		for _, v := range state {
			enumValue, err := flagsplugin.SetEnumString(v, State_value)
			if err != nil {
				return paths, err
			}
			m.State = append(m.State, State(enumValue))
		}
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("state", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	deleted, deletedSet, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("deleted", prefix))
	if err != nil {
		return paths, err
	}
	if deletedSet {
		m.Deleted = deleted
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("deleted", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSearchEndDevicesRequest adds flags to select fields in SearchEndDevicesRequest.
func AddSetFlagsForSearchEndDevicesRequest(flags *pflag.FlagSet, prefix string) {
	AddSetFlagsForApplicationIdentifiers(flags, flagsplugin.Prefix("application-ids", prefix))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("id-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("name-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("description-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringStringMapFlag(flagsplugin.Prefix("attributes-contain", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("dev-eui-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("join-eui-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("dev-addr-contains", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringSliceFlag(flagsplugin.Prefix("field-mask", prefix), ""))
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("order", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("limit", prefix), ""))
	flags.AddFlag(flagsplugin.NewUint32Flag(flagsplugin.Prefix("page", prefix), ""))
}

// SetFromFlags sets the SearchEndDevicesRequest message from flags.
func (m *SearchEndDevicesRequest) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	applicationIdsSet := flagsplugin.IsAnyPrefixSet(flags, flagsplugin.Prefix("application-ids", prefix))
	if applicationIdsSet {
		m.ApplicationIds = &ApplicationIdentifiers{}
		if setPaths, err := m.ApplicationIds.SetFromFlags(flags, flagsplugin.Prefix("application-ids", prefix)); err != nil {
			return paths, err
		} else {
			paths = append(paths, setPaths...)
		}
	}
	idContains, idContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("id-contains", prefix))
	if err != nil {
		return paths, err
	}
	if idContainsSet {
		m.IdContains = idContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("id-contains", prefix)))
	}
	nameContains, nameContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("name-contains", prefix))
	if err != nil {
		return paths, err
	}
	if nameContainsSet {
		m.NameContains = nameContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("name-contains", prefix)))
	}
	descriptionContains, descriptionContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("description-contains", prefix))
	if err != nil {
		return paths, err
	}
	if descriptionContainsSet {
		m.DescriptionContains = descriptionContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("description-contains", prefix)))
	}
	attributesContain, attributesContainSet, err := flagsplugin.GetStringStringMap(flags, flagsplugin.Prefix("attributes-contain", prefix))
	if err != nil {
		return paths, err
	}
	if attributesContainSet {
		m.AttributesContain = attributesContain
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("attributes-contain", prefix)))
	}
	devEuiContains, devEuiContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("dev-eui-contains", prefix))
	if err != nil {
		return paths, err
	}
	if devEuiContainsSet {
		m.DevEuiContains = devEuiContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("dev-eui-contains", prefix)))
	}
	joinEuiContains, joinEuiContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("join-eui-contains", prefix))
	if err != nil {
		return paths, err
	}
	if joinEuiContainsSet {
		m.JoinEuiContains = joinEuiContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("join-eui-contains", prefix)))
	}
	devAddrContains, devAddrContainsSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("dev-addr-contains", prefix))
	if err != nil {
		return paths, err
	}
	if devAddrContainsSet {
		m.DevAddrContains = devAddrContains
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("dev-addr-contains", prefix)))
	}
	fieldMask, fieldMaskSet, err := flagsplugin.GetStringSlice(flags, flagsplugin.Prefix("field-mask", prefix))
	if err != nil {
		return paths, err
	}
	if fieldMaskSet {
		m.FieldMask = gogo.SetFieldMask(fieldMask)
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("field-mask", prefix)))
	}
	order, orderSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("order", prefix))
	if err != nil {
		return paths, err
	}
	if orderSet {
		m.Order = order
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("order", prefix)))
	}
	limit, limitSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("limit", prefix))
	if err != nil {
		return paths, err
	}
	if limitSet {
		m.Limit = limit
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("limit", prefix)))
	}
	page, pageSet, err := flagsplugin.GetUint32(flags, flagsplugin.Prefix("page", prefix))
	if err != nil {
		return paths, err
	}
	if pageSet {
		m.Page = page
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("page", prefix)))
	}
	return paths, nil
}
