// Code generated by protoc-gen-go-flags. DO NOT EDIT.
// versions:
// - protoc-gen-go-flags v0.0.0-dev
// - protoc              v3.17.3
// source: lorawan-stack/api/secrets.proto

package ttnpb

import (
	flagsplugin "github.com/TheThingsIndustries/protoc-gen-go-flags/flagsplugin"
	pflag "github.com/spf13/pflag"
)

// AddSelectFlagsForSecret adds flags to select fields in Secret.
func AddSelectFlagsForSecret(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("key-id", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("key-id", prefix), false)))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("value", prefix), flagsplugin.SelectDesc(flagsplugin.Prefix("value", prefix), false)))
}

// SelectFromFlags outputs the fieldmask paths forSecret message from select flags.
func PathsFromSelectFlagsForSecret(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	keyId, keyIdSelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("key-id", prefix))
	if err != nil {
		return paths, err
	}
	if keyIdSelect && keyId {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("key-id", prefix)))
	}
	value, valueSelect, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("value", prefix))
	if err != nil {
		return paths, err
	}
	if valueSelect && value {
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("value", prefix)))
	}
	return paths, nil
}

// AddSetFlagsForSecret adds flags to select fields in Secret.
func AddSetFlagsForSecret(flags *pflag.FlagSet, prefix string) {
	flags.AddFlag(flagsplugin.NewStringFlag(flagsplugin.Prefix("key-id", prefix), ""))
	flags.AddFlag(flagsplugin.NewHexBytesFlag(flagsplugin.Prefix("value", prefix), ""))
}

// SetFromFlags sets the Secret message from flags.
func (m *Secret) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	keyId, keyIdSet, err := flagsplugin.GetString(flags, flagsplugin.Prefix("key-id", prefix))
	if err != nil {
		return paths, err
	}
	if keyIdSet {
		m.KeyId = keyId
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("key-id", prefix)))
	}
	value, valueSet, err := flagsplugin.GetBytes(flags, flagsplugin.Prefix("value", prefix))
	if err != nil {
		return paths, err
	}
	if valueSet {
		m.Value = value
		paths = append(paths, flagsplugin.FieldMaskFlag(flagsplugin.Prefix("value", prefix)))
	}
	return paths, nil
}
